import type { Product, SystemComponent } from '../../types/system';
import { BatterySymbol } from './symbols/BatterySymbol';
import { MpptSymbol } from './symbols/MpptSymbol';
import { SolarArraySymbol } from './symbols/SolarArraySymbol';
import { InverterChargerSymbol } from './symbols/InverterChargerSymbol';
import { LynxDistributionSymbol } from './symbols/LynxDistributionSymbol';
import { FuseSymbol } from './symbols/FuseSymbol';
import { GenericSymbol } from './symbols/GenericSymbol';
import { Terminal } from './Terminal';
import { getEffectiveTerminals } from '../../utils/effectiveTerminals';
import { getProductImageUrl, resolveProductImageUrl } from '../../utils/productImages';
import type { BusColorMap } from '../../utils/busColors';
import { orientationTransform } from '../../utils/componentOrientation';

interface Props {
  component: SystemComponent;
  product: Product;
  selected: boolean;
  pendingFromTerminal: string | null;
  busColors: BusColorMap;
  onSelect: (id: string) => void;
  onDragStart: (id: string, e: React.MouseEvent) => void;
  onTerminalMouseDown: (compId: string, termId: string, e: React.MouseEvent) => void;
}

function Symbol({
  product,
  component,
  selected,
}: {
  product: Product;
  component: SystemComponent;
  selected: boolean;
}) {
  const w = product.width;
  const h = product.height;
  const imageUrl = resolveProductImageUrl(product.imageUrl ?? getProductImageUrl(product.productType));

  if (imageUrl) {
    return (
      <>
        <image
          href={imageUrl}
          x={-w / 2}
          y={-h / 2}
          width={w}
          height={h}
        />
        {selected && (
          <rect
            x={-w / 2 - 2}
            y={-h / 2 - 2}
            width={w + 4}
            height={h + 4}
            rx={7}
            fill="none"
            stroke="#1769d2"
            strokeWidth={2.5}
            opacity={0.85}
          />
        )}
      </>
    );
  }

  switch (product.productType) {
    case 'battery':
      return <BatterySymbol product={product} component={component} selected={selected} />;
    case 'mppt':
      return <MpptSymbol product={product} selected={selected} />;
    case 'solar_array':
      return <SolarArraySymbol product={product} component={component} selected={selected} />;
    case 'inverter_charger':
      return <InverterChargerSymbol product={product} selected={selected} />;
    case 'dc_distribution':
    case 'busbar':
      return <LynxDistributionSymbol product={product} selected={selected} />;
    case 'fuse':
    case 'breaker':
      return <FuseSymbol product={product} component={component} selected={selected} />;
    default:
      return <GenericSymbol product={product} selected={selected} />;
  }
}

export function ComponentNode({
  component,
  product,
  selected,
  pendingFromTerminal,
  busColors,
  onSelect,
  onDragStart,
  onTerminalMouseDown,
}: Props) {
  const label = component.label ?? product.name;
  const displayLabel = label.length > 22 ? label.slice(0, 21) + '...' : label;
  const rotation = component.rotationDeg ?? 0;
  const terminals = getEffectiveTerminals(product, component);

  return (
    <g
      transform={`translate(${component.x}, ${component.y})`}
      style={{ cursor: 'grab' }}
      onMouseDown={(e) => {
        if (e.button !== 0) return;
        e.preventDefault();
        onDragStart(component.id, e);
      }}
      onClick={(e) => {
        e.stopPropagation();
        onSelect(component.id);
      }}
    >
      <g transform={orientationTransform(rotation)}>
        <Symbol product={product} component={component} selected={selected} />

        {/* Auto-generated badge */}
        {component.autoGenerated && (
          <g transform={`translate(${-product.width / 2 + 8}, ${-product.height / 2 + 8})`}>
            <circle r={5} fill="#fff7e7" stroke="#c98518" strokeWidth={1} />
            <text textAnchor="middle" dominantBaseline="middle" fill="#935f0d" fontSize={7} fontWeight={800}>A</text>
          </g>
        )}

        {/* Terminals */}
        {terminals.map((t) => (
          <Terminal
            key={t.id}
            terminal={t}
            componentId={component.id}
            isHighlighted={pendingFromTerminal !== null}
            isPending={false}
            busColors={busColors}
            onMouseDown={onTerminalMouseDown}
          />
        ))}
      </g>

      {/* Component label below */}
      <text
        x={0}
        y={product.height / 2 + 14}
        textAnchor="middle"
        fill={selected ? '#1769d2' : '#33435a'}
        fontSize={10}
        fontWeight={selected ? 900 : 800}
        style={{ userSelect: 'none', pointerEvents: 'none' }}
      >
        {displayLabel}
      </text>
    </g>
  );
}
