import { Fragment } from 'react';
import type { BomRow } from '../../types/system';
import { fmt } from '../../utils/priceCalculations';

interface Props {
  rows: BomRow[];
}

export function BomTable({ rows }: Props) {
  if (rows.length === 0) {
    return <div className="empty-state">No components in system.</div>;
  }

  let currentSection = '';

  return (
    <div style={{ overflowX: 'auto', overflowY: 'auto', maxHeight: '100%' }}>
      <table className="bom-table">
        <thead>
          <tr>
            <th>Part</th>
            <th>Manufacturer</th>
            <th>Description</th>
            <th style={{ textAlign: 'center' }}>Qty</th>
            <th style={{ textAlign: 'right' }}>Unit MSRP</th>
            <th style={{ textAlign: 'right' }}>Ext MSRP</th>
            <th style={{ textAlign: 'right' }}>Unit OEM</th>
            <th style={{ textAlign: 'right' }}>Ext OEM</th>
            <th>Source</th>
            <th>Auto</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => {
            const showSection = row.section !== currentSection;
            if (showSection) currentSection = row.section;

            return (
              <Fragment key={row.id}>
                {showSection && (
                  <tr className="bom-section-row">
                    <td colSpan={10}>{row.section}</td>
                  </tr>
                )}
                <tr className={row.autoGenerated ? 'bom-row-auto' : 'bom-row'}>
                  <td style={{ fontWeight: 800, color: '#182235' }}>{row.partName}</td>
                  <td>{row.manufacturer}</td>
                  <td style={{ maxWidth: 200 }}>
                    <span title={row.description}>
                      {row.description.length > 40 ? row.description.slice(0, 39) + '...' : row.description}
                    </span>
                  </td>
                  <td style={{ textAlign: 'center' }}>
                    {row.quantity}
                  </td>
                  <td style={{ textAlign: 'right' }}>{fmt(row.unitMsrpUsd)}</td>
                  <td style={{ textAlign: 'right' }}>{fmt(row.extendedMsrpUsd)}</td>
                  <td style={{ textAlign: 'right', color: '#2f9461', fontWeight: 800 }}>{fmt(row.unitOemUsd)}</td>
                  <td style={{ textAlign: 'right', color: '#2f9461', fontWeight: 800 }}>{fmt(row.extendedOemUsd)}</td>
                  <td style={{ color: '#6d7b90', fontSize: 9, fontWeight: 700 }}>{row.priceSource}</td>
                  <td style={{ textAlign: 'center' }}>
                    {row.autoGenerated && <span style={{ color: '#935f0d', fontSize: 9, fontWeight: 900 }}>Auto</span>}
                  </td>
                </tr>
              </Fragment>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}
