import type { SystemDesign, BomRow, BomSection, Product } from '../types/system';
import { SECTION_FOR_TYPE } from '../data/electricalRules';
import { getFuseHolderForProduct } from './fuseHolders';

function sectionFor(productType: string): BomSection {
  return (SECTION_FOR_TYPE[productType] as BomSection) ?? 'Accessories';
}

export function buildBom(
  system: SystemDesign,
  products: Map<string, Product>
): BomRow[] {
  const rowsByKey = new Map<string, BomRow>();

  for (const comp of system.components) {
    if (comp.includeInBom === false) continue;

    const product = products.get(comp.productId);
    if (!product) continue;

    const unitMsrp = comp.customPriceUsd ?? product.msrpUsd ?? null;
    const unitOem = product.oemPriceUsd ?? (unitMsrp != null
      ? unitMsrp * (1 - system.assumptions.defaultOemDiscountPercent / 100)
      : null);

    const key = [
      product.id,
      unitMsrp ?? '',
      unitOem ?? '',
      comp.customPriceUsd != null ? 'manual' : product.source ?? 'Unknown',
      comp.autoGenerated ? 'auto' : 'manual',
      comp.userNotes ?? (comp.autoGenerated ? 'Auto-generated' : ''),
    ].join('|');

    const existing = rowsByKey.get(key);
    if (existing) {
      existing.quantity += comp.quantity;
      existing.extendedMsrpUsd = unitMsrp != null ? unitMsrp * existing.quantity : null;
      existing.extendedOemUsd = unitOem != null ? unitOem * existing.quantity : null;
    } else {
      rowsByKey.set(key, {
        id: key,
        section: sectionFor(product.productType),
        productType: product.productType,
        manufacturer: product.manufacturer,
        partName: product.name,
        productUrl: product.productUrl,
        description: product.description ?? '',
        quantity: comp.quantity,
        unitMsrpUsd: unitMsrp,
        extendedMsrpUsd: unitMsrp != null ? unitMsrp * comp.quantity : null,
        unitOemUsd: unitOem,
        extendedOemUsd: unitOem != null ? unitOem * comp.quantity : null,
        priceSource: comp.customPriceUsd != null ? 'Manual override' : (product.source ?? 'Unknown'),
        autoGenerated: comp.autoGenerated ?? false,
        notes: comp.userNotes ?? (comp.autoGenerated ? 'Auto-generated' : ''),
        componentId: comp.id,
      });
    }

    if (comp.includeFuseHolder === true) {
      const holder = getFuseHolderForProduct(product);
      if (!holder) continue;

      const holderKey = [
        comp.fuseHolderProductId ?? holder.id,
        holder.unitMsrpUsd ?? '',
        holder.unitOemUsd ?? '',
        holder.priceSource,
      ].join('|');

      const existingHolder = rowsByKey.get(holderKey);
      if (existingHolder) {
        existingHolder.quantity += comp.quantity;
        existingHolder.extendedMsrpUsd = holder.unitMsrpUsd != null
          ? holder.unitMsrpUsd * existingHolder.quantity
          : null;
        existingHolder.extendedOemUsd = holder.unitOemUsd != null
          ? holder.unitOemUsd * existingHolder.quantity
          : null;
        continue;
      }

      rowsByKey.set(holderKey, {
        id: holderKey,
        section: 'Protection',
        productType: 'accessory',
        manufacturer: holder.manufacturer,
        partName: holder.name,
        description: holder.description,
        quantity: comp.quantity,
        unitMsrpUsd: holder.unitMsrpUsd,
        extendedMsrpUsd: holder.unitMsrpUsd != null ? holder.unitMsrpUsd * comp.quantity : null,
        unitOemUsd: holder.unitOemUsd,
        extendedOemUsd: holder.unitOemUsd != null ? holder.unitOemUsd * comp.quantity : null,
        priceSource: holder.priceSource,
        autoGenerated: true,
        notes: `Fuse holder for ${product.name}`,
        componentId: comp.id,
      });
    }
  }

  const SECTION_ORDER: BomSection[] = [
    'Energy Storage',
    'Charging Sources',
    'Power Conversion',
    'DC Distribution',
    'AC Distribution',
    'Protection',
    'Cabling',
    'Monitoring & Control',
    'Accessories',
  ];

  const rows = Array.from(rowsByKey.values());

  rows.sort((a, b) => {
    const ai = SECTION_ORDER.indexOf(a.section);
    const bi = SECTION_ORDER.indexOf(b.section);
    if (ai !== bi) return ai - bi;
    return a.partName.localeCompare(b.partName);
  });

  return rows;
}
