import type { SystemDesign, BomRow, BomSection, Product } from '../types/system';
import { SECTION_FOR_TYPE } from '../data/electricalRules';
import { getFuseHolderForProduct } from './fuseHolders';
import { resolveFuseSlot } from './distributionTopology';
import { findFuseProductByStyleRating } from './fuseSelection';

function sectionFor(productType: string): BomSection {
  return (SECTION_FOR_TYPE[productType] as BomSection) ?? 'Accessories';
}

export function buildBom(
  system: SystemDesign,
  products: Map<string, Product>
): BomRow[] {
  const rowsByKey = new Map<string, BomRow>();

  for (const comp of system.components) {
    if (comp.includeInBom === false) continue;

    const product = products.get(comp.productId);
    if (!product) continue;

    const unitMsrp = comp.customPriceUsd ?? product.msrpUsd ?? null;
    const unitOem = product.oemPriceUsd ?? (unitMsrp != null
      ? unitMsrp * (1 - system.assumptions.defaultOemDiscountPercent / 100)
      : null);

    const key = [
      product.id,
      unitMsrp ?? '',
      unitOem ?? '',
      comp.customPriceUsd != null ? 'manual' : product.source ?? 'Unknown',
      comp.autoGenerated ? 'auto' : 'manual',
      comp.userNotes ?? (comp.autoGenerated ? 'Auto-generated' : ''),
    ].join('|');

    const existing = rowsByKey.get(key);
    if (existing) {
      existing.quantity += comp.quantity;
      existing.extendedMsrpUsd = unitMsrp != null ? unitMsrp * existing.quantity : null;
      existing.extendedOemUsd = unitOem != null ? unitOem * existing.quantity : null;
    } else {
      rowsByKey.set(key, {
        id: key,
        section: sectionFor(product.productType),
        productType: product.productType,
        manufacturer: product.manufacturer,
        partName: product.name,
        productUrl: product.productUrl,
        description: product.description ?? '',
        quantity: comp.quantity,
        unitMsrpUsd: unitMsrp,
        extendedMsrpUsd: unitMsrp != null ? unitMsrp * comp.quantity : null,
        unitOemUsd: unitOem,
        extendedOemUsd: unitOem != null ? unitOem * comp.quantity : null,
        priceSource: comp.customPriceUsd != null ? 'Manual override' : (product.source ?? 'Unknown'),
        autoGenerated: comp.autoGenerated ?? false,
        notes: comp.userNotes ?? (comp.autoGenerated ? 'Auto-generated' : ''),
        componentId: comp.id,
      });
    }

    // Fuses inserted into integrated distribution fuse slots (e.g. Lynx Distributor)
    // become their own priced Protection line items, aggregated by fuse product.
    for (const slot of product.distributionTopology?.fuseSlots ?? []) {
      const resolved = resolveFuseSlot(comp, slot);
      if (!resolved.installed || resolved.ratingA == null) continue;
      if (resolved.state.includeInBom === false) continue;

      const fuseStyle = slot.fuseStyle ?? 'MEGA';
      const fuseProduct = resolved.state.fuseProductId
        ? products.get(resolved.state.fuseProductId)
        : findFuseProductByStyleRating(products.values(), fuseStyle, resolved.ratingA);
      if (!fuseProduct) continue;

      const fuseUnitMsrp = fuseProduct.msrpUsd ?? null;
      const fuseUnitOem = fuseProduct.oemPriceUsd ?? (fuseUnitMsrp != null
        ? fuseUnitMsrp * (1 - system.assumptions.defaultOemDiscountPercent / 100)
        : null);

      const fuseKey = [
        'slot-fuse',
        fuseProduct.id,
        fuseUnitMsrp ?? '',
        fuseUnitOem ?? '',
        fuseProduct.source ?? 'Unknown',
      ].join('|');

      const existingFuse = rowsByKey.get(fuseKey);
      if (existingFuse) {
        existingFuse.quantity += comp.quantity;
        existingFuse.extendedMsrpUsd = fuseUnitMsrp != null ? fuseUnitMsrp * existingFuse.quantity : null;
        existingFuse.extendedOemUsd = fuseUnitOem != null ? fuseUnitOem * existingFuse.quantity : null;
      } else {
        rowsByKey.set(fuseKey, {
          id: fuseKey,
          section: 'Protection',
          productType: 'fuse',
          manufacturer: fuseProduct.manufacturer,
          partName: fuseProduct.name,
          productUrl: fuseProduct.productUrl,
          description: fuseProduct.description ?? '',
          quantity: comp.quantity,
          unitMsrpUsd: fuseUnitMsrp,
          extendedMsrpUsd: fuseUnitMsrp != null ? fuseUnitMsrp * comp.quantity : null,
          unitOemUsd: fuseUnitOem,
          extendedOemUsd: fuseUnitOem != null ? fuseUnitOem * comp.quantity : null,
          priceSource: fuseProduct.source ?? 'Unknown',
          autoGenerated: true,
          notes: `${slot.label} fuse for ${product.name}`,
          componentId: comp.id,
        });
      }
    }

    if (comp.includeFuseHolder === true) {
      const holder = getFuseHolderForProduct(product);
      if (!holder) continue;

      const holderKey = [
        comp.fuseHolderProductId ?? holder.id,
        holder.unitMsrpUsd ?? '',
        holder.unitOemUsd ?? '',
        holder.priceSource,
      ].join('|');

      const existingHolder = rowsByKey.get(holderKey);
      if (existingHolder) {
        existingHolder.quantity += comp.quantity;
        existingHolder.extendedMsrpUsd = holder.unitMsrpUsd != null
          ? holder.unitMsrpUsd * existingHolder.quantity
          : null;
        existingHolder.extendedOemUsd = holder.unitOemUsd != null
          ? holder.unitOemUsd * existingHolder.quantity
          : null;
        continue;
      }

      rowsByKey.set(holderKey, {
        id: holderKey,
        section: 'Protection',
        productType: 'accessory',
        manufacturer: holder.manufacturer,
        partName: holder.name,
        description: holder.description,
        quantity: comp.quantity,
        unitMsrpUsd: holder.unitMsrpUsd,
        extendedMsrpUsd: holder.unitMsrpUsd != null ? holder.unitMsrpUsd * comp.quantity : null,
        unitOemUsd: holder.unitOemUsd,
        extendedOemUsd: holder.unitOemUsd != null ? holder.unitOemUsd * comp.quantity : null,
        priceSource: holder.priceSource,
        autoGenerated: true,
        notes: `Fuse holder for ${product.name}`,
        componentId: comp.id,
      });
    }
  }

  const SECTION_ORDER: BomSection[] = [
    'Energy Storage',
    'Charging Sources',
    'Power Conversion',
    'DC Distribution',
    'AC Distribution',
    'Protection',
    'Cabling',
    'Monitoring & Control',
    'Accessories',
  ];

  const rows = Array.from(rowsByKey.values());

  rows.sort((a, b) => {
    const ai = SECTION_ORDER.indexOf(a.section);
    const bi = SECTION_ORDER.indexOf(b.section);
    if (ai !== bi) return ai - bi;
    return a.partName.localeCompare(b.partName);
  });

  return rows;
}
