import type { BomRow, CableLengthSummaryItem } from '../types/system';
import type { ConnectorSummaryItem } from './cableSummary';
import { formatFeetAndInches } from './cableSummary';

function esc(value: string | number | null | boolean): string {
  if (value == null) return '';
  const str = String(value);
  if (str.includes(',') || str.includes('"') || str.includes('\n')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

export function exportBomCsv(
  rows: BomRow[],
  systemName: string,
  cableSummary: CableLengthSummaryItem[] = [],
  connectorSummary: ConnectorSummaryItem[] = []
): void {
  const headers = [
    'Section',
    'Product Type',
    'Manufacturer',
    'Part Name',
    'Description',
    'Quantity',
    'Unit MSRP (USD)',
    'Extended MSRP (USD)',
    'Price Source',
    'Auto-Generated',
    'Notes',
  ];

  const csvRows = [
    headers.map(esc).join(','),
    ...rows.map((r) =>
      [
        r.section,
        r.productType,
        r.manufacturer,
        r.partName,
        r.description,
        r.quantity,
        r.unitMsrpUsd,
        r.extendedMsrpUsd,
        r.priceSource,
        r.autoGenerated ? 'Yes' : 'No',
        r.notes,
      ]
        .map(esc)
        .join(',')
    ),
  ];

  if (cableSummary.length > 0) {
    csvRows.push('');
    csvRows.push(['Cable Summary'].map(esc).join(','));
    csvRows.push(['Cable Gauge', 'Color', 'Type', 'Total Length', 'Cable Count'].map(esc).join(','));
    csvRows.push(...cableSummary.map((item) =>
      [
        item.gauge,
        item.color || '',
        item.type || '',
        formatFeetAndInches(item.totalLengthFt),
        item.cableCount,
      ]
        .map(esc)
        .join(',')
    ));
  }

  if (connectorSummary.length > 0) {
    csvRows.push('');
    csvRows.push(['Lugs & Connectors'].map(esc).join(','));
    csvRows.push(['Connector', 'Hole Size', 'Gauge', 'Qty', 'Est. Unit (USD)', 'Est. Extended (USD)'].map(esc).join(','));
    csvRows.push(...connectorSummary.map((item) =>
      [
        item.label,
        item.holeSize ?? '',
        item.gauge ?? '',
        item.count,
        item.estUnitMsrpUsd,
        item.estExtendedMsrpUsd,
      ]
        .map(esc)
        .join(',')
    ));
  }

  const blob = new Blob([csvRows.join('\n')], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${systemName.replace(/\s+/g, '_')}_BOM.csv`;
  a.click();
  URL.revokeObjectURL(url);
}
